<a href="https://colab.research.google.com/github/josh-kindhart/Python-Practice/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
from datetime import datetime
import pandas as pd
import pandas_datareader.data as web
import matplotlib.pyplot as plt

api_key = '26E0EWOJLXTIUY3V'
df = web.DataReader("AAPL", "av-intraday", start=datetime(2017, 2, 9),
                           api_key=api_key)

In [2]:
df['DateTime'] = df.index
df.reset_index(drop=True, inplace=True)
df.columns = ['Open','High','Low','Close','Volume','DateTime']
df = df[['DateTime','Open','High','Low','Close','Volume']]
df['DateTime'] = pd.to_datetime(df['DateTime'])

In [3]:
display(df)

                 DateTime     Open     High      Low    Close  Volume
0     2023-07-21 04:00:00  192.721  193.141  192.721  193.130     915
1     2023-07-21 04:01:00  193.130  193.131  192.810  192.940    1128
2     2023-07-21 04:02:00  192.911  193.041  192.840  193.040     175
3     2023-07-21 04:03:00  192.891  193.021  192.890  193.020      36
4     2023-07-21 04:04:00  192.990  193.031  192.960  193.020     244
...                   ...      ...      ...      ...      ...     ...
20093 2023-08-18 19:55:00  174.630  174.650  174.600  174.625     321
20094 2023-08-18 19:56:00  174.640  174.650  174.600  174.650     530
20095 2023-08-18 19:57:00  174.625  174.680  174.600  174.680     766
20096 2023-08-18 19:58:00  174.675  174.700  174.650  174.650     550
20097 2023-08-18 19:59:00  174.690  174.700  174.660  174.700    2038

[20098 rows x 6 columns]